/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme;

import Kontroler.Controller;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.JButton;

/**
 *
 * 
 */
public class FrmPocetna extends javax.swing.JFrame {

    /**
     * Creates new form FrmPocetna
     */
    public FrmPocetna() {
        initComponents();
        setTitle("Pocetna forma");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrganic = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        btnZaustavi = new javax.swing.JButton();
        btnPokreni = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPodešavanjeBaze = new javax.swing.JMenu();
        jMenuItemPodesavanjeBaze = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOrganic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrganic.setText("Projekat- Picerija");

        lblStudent.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblStudent.setText("Anastasija Mitic");

        btnZaustavi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZaustavi.setForeground(new java.awt.Color(102, 0, 0));
        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.setEnabled(false);
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        btnPokreni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        jMenuPodešavanjeBaze.setText("Podešavanja");

        jMenuItemPodesavanjeBaze.setText("Podešavanje baze");
        jMenuItemPodesavanjeBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPodesavanjeBazeActionPerformed(evt);
            }
        });
        jMenuPodešavanjeBaze.add(jMenuItemPodesavanjeBaze);

        jMenuBar1.add(jMenuPodešavanjeBaze);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudent)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrganic, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblOrganic, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
                btnPokreni.setEnabled(true);
                btnZaustavi.setEnabled(false);
                Controller.getInstance().zaustaviServer();
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void jMenuItemPodesavanjeBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPodesavanjeBazeActionPerformed
        
        FrmPodesavanja frm=new FrmPodesavanja(null, false);
        try {
            Properties properties = new Properties();
            properties.load(new FileInputStream("config/dbconfig.properties"));
            
             frm.getTxtKorisnickoIme().setText(properties.getProperty("username"));
             frm.getTxtPassword().setText(properties.getProperty("password"));
             frm.getTxtURL().setText(properties.getProperty("url"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemPodesavanjeBazeActionPerformed

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        btnPokreni.setEnabled(false);
                btnZaustavi.setEnabled(true);
                 Controller.getInstance().pokreniServer();
    }//GEN-LAST:event_btnPokreniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPocetna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editolblOrganic

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPocetna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPodesavanjeBaze;
    private javax.swing.JMenu jMenuPodešavanjeBaze;
    private javax.swing.JLabel lblOrganic;
    private javax.swing.JLabel lblStudent;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnPokreni() {
        return btnPokreni;
    }

    public JButton getBtnZaustavi() {
        return btnZaustavi;
    }

    public void pokreniAddActionListener(ActionListener actionListener) {
        btnPokreni.addActionListener(actionListener);
    }

    public void podesavanjeAddActionListener(ActionListener actionListener) {
        jMenuItemPodesavanjeBaze.addActionListener(actionListener);
    }

    public void zaustaviAddActionListener(ActionListener actionListener) {
        btnZaustavi.addActionListener(actionListener);
    }

  
    
    



}
