/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forme.prikaz;

import domen.Korisnik;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.ImageIcon; 

/**
 *
 * 
 */
public class FrmMain extends javax.swing.JFrame {
    ImageIcon slikaPizza = new ImageIcon("pizza.jpg");
    ImageIcon slikaLogo = new ImageIcon("logo2.png");
    
    /**
     * Creates new form MainForma
     */
    public FrmMain() {
        initComponents();
        // setVisible(true);
         this.setExtendedState(JFrame.MAXIMIZED_BOTH);
         Sesija.Sesija.getInstanca().setGlavna(this);
         logo.setText("");
         slika.setText("");
         logo.setIcon(slikaLogo);
         slika.setIcon(slikaPizza);
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        slika = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuKreirajPicu = new javax.swing.JMenuItem();
        jMenuPretraziPice = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuKreirajRacun = new javax.swing.JMenuItem();
        jMenuPretraziRacun = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Odjava");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dobrodošli na aplikaciju koja pravi i prodaje pice ");
        jLabel1.setToolTipText("");
        jLabel1.setFocusTraversalPolicyProvider(true);

        slika.setText("jLabel3");
        slika.setPreferredSize(new java.awt.Dimension(1024, 768));

        logo.setText("jLabel4");
        logo.setMaximumSize(new java.awt.Dimension(534, 415));
        logo.setPreferredSize(new java.awt.Dimension(534, 415));

        jMenu1.setText("Pica");
        jMenu1.setToolTipText("");

        jmenuKreirajPicu.setText("Kreiraj picu");
        jmenuKreirajPicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuKreirajPicuActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuKreirajPicu);

        jMenuPretraziPice.setText("Pretraži picu");
        jMenuPretraziPice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPretraziPiceActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPretraziPice);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Racun");

        jMenuKreirajRacun.setText("Kreiraj račun");
        jMenuKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKreirajRacunActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuKreirajRacun);

        jMenuPretraziRacun.setText("Pretraži račun");
        jMenuPretraziRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPretraziRacunActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPretraziRacun);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(slika, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slika, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(346, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(619, 619, 619))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPretraziPiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPretraziPiceActionPerformed
       new FrmPretragaPica(this, false).setVisible(true);
    }//GEN-LAST:event_jMenuPretraziPiceActionPerformed

    private void jMenuPretraziRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPretraziRacunActionPerformed
        new FrmPretraziRacun(this, false).setVisible(true);
    }//GEN-LAST:event_jMenuPretraziRacunActionPerformed

    private void jmenuKreirajPicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuKreirajPicuActionPerformed
     new FrmKreirajPicu(this, false).setVisible(true);
    }//GEN-LAST:event_jmenuKreirajPicuActionPerformed

    private void jMenuKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKreirajRacunActionPerformed
        new FrmKreirajRacun(this, false).setVisible(true);
    }//GEN-LAST:event_jMenuKreirajRacunActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            komunikacija.Komunikacija.getInstanca().odjaviSe((Korisnik) Sesija.Sesija.getInstanca().vratiParametar("Korisnik"));
        } catch (Exception ex) {
           
        }
        this.dispose();
       new FrmPocetna().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuKreirajRacun;
    private javax.swing.JMenuItem jMenuPretraziPice;
    private javax.swing.JMenuItem jMenuPretraziRacun;
    private javax.swing.JMenuItem jmenuKreirajPicu;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel slika;
    // End of variables declaration//GEN-END:variables

   
    
}
